@startuml

usecase "delete tweet" as UC
actor "User" as US

boundary DeleteTweetForm
control TweetControl

entity DeletableTweet
entity Retweet

DeletableTweet "1" *-- "0..*" Retweet

US --> DeleteTweetForm
DeleteTweetForm --> TweetControl
TweetControl --> DeletableTweet : delete
Tweet --> Tweet : "delete retweet"


@enduml
