@startuml

package tweet <<core-domain>> {
    class Tweet  <<Root>>
    class Retweet
    class Reply
    interface To

    Tweet <|-- Retweet
    Tweet <|-- Reply
    Retweet "0..1" o-- "1" Tweet
    Tweet "1" *-- "0..*" Retweet

    Reply "1" o-- "1" To
}



package user {
    class User <<Root>>
    class LoginUser {
        --
        getFollowingUsers() : List<FollowingUser>
    }

    User <|-- LoginUser

    class FollowingUser
    User "1" *-- "0..*" FollowingUser
}

User "1" *-- "0..*" Tweet : post
To <|.. User

package timeline {
    class TimeLine <<Root>> {
        --
        + {static} create(loginUser : LoginUser, followings : List<FollowingUser>) : TimeLine
    }
}

TimeLine "1" o-- "0..*" Tweet
TimeLine --> LoginUser
TimeLine --> FollowingUser




@enduml
