@startuml

package tweet {
    class Tweet
    class Retweet
    class Reply
}

Tweet <|-- Retweet
Tweet <|-- Reply
Retweet "0..1" o-- "1" Tweet
Tweet "1" *-- "0..*" Retweet

package usr {
    class User
    class Follower
}

User "1" *-- "0..*" Tweet : post
Reply "1" o-- "1" User : To
User "1" *-- "1..*" Follower
User "1" o-- "0..*" User : following

package timeline {
    class Timeline
}

Timeline "1" o-- "0..*" Tweet



@enduml
